const btn1 = document.getElementById('btn1')
const btn2 = document.getElementById('btn2')
const test = document.getElementById('test')

btn1.onclick = () => {
    alert("Alert 1")
}

btn2.onclick = () => {
    alert("Alert 2")
}

test.onclick = () => {
    alert("LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, LAG, ")
}